version: '3.9'

services:
  frontend:
    build: ./frontend
    
    ports:
      - "${PORT}:${PORT}"

    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    
    env_file:
      - .env

    restart: always

  tester:
    build: ./tester

    ports:
        - "${TESTER_PORT}:${TESTER_PORT}"
    
    volumes:
        - ./tester/src:/usr/src/app/src
        - ./tester/static/static:/usr/src/app/static/static
        - test-images:/usr/src/app/static/test-images

    env_file:
      - .env

    restart: always

volumes:
  test-images: