version: '3.9'

services:
    frontend:
        build: ./frontend

        ports:
            - "${PORT}:${PORT}"

        volumes:
            - ./frontend:/usr/src/app

        env_file:
            - .env

        restart: always

    backend:
        build: ./backend

        ports:
            - "${BACKEND_PORT}:${BACKEND_PORT}"

        volumes:
            - ./backend:/usr/src/app
            - images:/usr/src/app/static

        env_file:
            - .env

        restart: always
    
    database:
        build: ./database

        expose:
            - "5432"

        volumes:
            - app-pgdata:/var/lib/postgresql/data

        env_file:
            - .env

        tty: true
        stdin_open: true

        restart: always

volumes:
    app-pgdata:
    images: